#!/bin/bash

. /usr/sbin/tc-common

if docker ps | grep -q "tc-wazuh"; then
        docker exec -it tc-wazuh /var/ossec/bin/ossec-control stop
	docker stop tc-wazuh && docker rm tc-wazuh
else
	echo "OSSEC already stopped."
fi
